server:
  port: 8764

spring:
  application:
    name: eureka-consumer
  devtools:
    restart:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

