server:
  port: 8763

spring:
  application:
    name: eureka-provider
  devtools:
    restart:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
